version: '3'
services:
  zookernel:
    build: .
    image: geolabs/mapmint
    ports:
      - "80:80"
    volumes:
      - ./docker/main.cfg:/usr/lib/cgi-bin/main.cfg
      - ./docker/oas.cfg:/usr/lib/cgi-bin/oas.cfg
      - ./docker/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./zoo-project/zoo-services/utils/open-api/server/publish.py:/usr/lib/cgi-bin/publish.py
      - ./zoo-project/zoo-services/utils/open-api/server/subscriber.py:/usr/lib/cgi-bin/subscriber.py
      - ./docker/.htaccess:/var/www/html/.htaccess
      - ./zoo-project/zoo-services/utils/open-api/templates/index.html:/var/www/index.html
      - ./zoo-project/zoo-services/utils/open-api/static:/var/www/html/static
      - /home/reliabilitygorup/Data/Code/mapmint/mapmint-ui/templates:/mapmint/mapmint-ui/templates
      - /home/reliabilitygorup/Data/Code/mapmint/public_map:/mapmint/public_map
    depends_on:
      - pgbouncer
    environment:
      - LC_ALL=en_US.utf-8
      - LANG=en_US.itf-8
      - ZOO_REDIS_HOST=redis
  websocketd:
    build: ./docker/websocketd
    ports:
      - 8888:8888
    environment:
      - ZOO_REDIS_HOST=redis
    volumes:
      - ./zoo-project/zoo-services/utils/open-api/server/subscriber.py:/shell.py
    command: ["--port=8888", "/shell.py"]
  pg:
    image: postgis/postgis:10-2.5-alpine #postgres:9.6.18-alpine
    restart: always
    environment:
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: zoo
      POSTGRES_DB: zoo
    volumes:
      # Load the zoo kernel schema
      - ./zoo-project/zoo-kernel/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./mapmint/template/sql/mmdb.sql:/docker-entrypoint-initdb.d/2-mmdb.sql
      - ./mapmint/template/sql/indicators.sql:/docker-entrypoint-initdb.d/3-indicators.sql
      - ./mapmint/template/sql/tables.sql:/docker-entrypoint-initdb.d/4-tables.sql
      - ./mapmint:/home/reliabilitygorup/Data/Code/mapmint
  pgbouncer:
    image: edoburu/pgbouncer:1.8.1
    environment:
      DATABASE_URL: "postgres://zoo:zoo@pg/zoo"
      MAX_CLIENT_CONN: 1000
      MAX_DB_CONNECTIONS: 100
      DEFAULT_POOL_SIZE: 100
      POOL_MODE: transaction
    ports:
      - "5432:5432"
    depends_on:
      - pg
  redis:
    image: redis:6.0.9
